### ISSUE TITLE
Documentation: Mention that "url" method might return a URI::file object

### ISSUE THREAD

**Issue by tommystanton** [sdt/Test-SVN-Repo#7]
I noticed that the `url` method might [return a URI::file object](https://github.com/sdt/Test-SVN-Repo/blob/c02b1daeb4b0ae23701c7d008f9d91eef8ba596d/lib/Test/SVN/Repo.pm#L42).

Could we mention this in the POD, or maybe call the `as_string` method on the URI::file object before returning it?

**Comment by sdt** [comment]
I think I might go with the as_string approach.

Normally I'd lean toward returning an object over a string, but given the other return value is a string, its probably better to return the same type in all cases.

Thanks for picking that up.

**Comment by sdt** [comment]
Fixed in release 0.009
